### ISSUE TITLE
Missing Metadata information ❓ 

### ISSUE THREAD

**Issue by MatthewSzurkowski** [GBADsInformatics/GBADsDataSearchUI#10]
When a search result is clicked on, the following fields are not populating with information:

- Authors
- Data source
- Columns included
- Measured values
- Source
- Contact point
- API Call
- Download Metadata
- Start & End year

API call I use to fetch this information could have been updated. I'll double check and then check with Kassy if anything comes up.

**Comment by MatthewSzurkowski** [comment]
The API Call and Download Metadata buttons should be removed if no such links can be found.

**Comment by kassyray** [comment]
I'll work on this. Depending on the metadata & data source, there may be missing and/or additional fields. Can the fields in the front end be updated dynamically based on what is returned from the API?

**Comment by kassyray** [comment]
Added an ETL repo to validate schema prior to ingestion into graphdb. Will be using pydantic

**Comment by kassyray** [comment]
This is being completed on a separate branch and will merge this week.
