### ISSUE TITLE
Weird behaviour retrieving metadata

### ISSUE THREAD

**Issue by kassyray** [GBADsInformatics/GBADsDataSearchUI#16]
![Image](https://github.com/GBADsInformatics/GBADsDataSearchUI/assets/44474665/fd28f9f0-727b-4e33-912f-3221cbec7bf7)

The query "Ethiopia", "Cattle", "Bovine" retrieves nothing when it does work: https://gbadske.org/meta-api/datasets?countries=Ethiopia&species=Cattle,Bovine

If just the words "Ethiopia" and "Cattle" it works. 

![Image](https://github.com/GBADsInformatics/GBADsDataSearchUI/assets/44474665/dcb8a7f8-a4b8-41ab-be2d-5ef3770b1dbb)

I think this could be a bug with the API call?

**Comment by MatthewSzurkowski** [comment]
Resolved with 085d0d0da5e6cef43b87f6fe74216cd3633316d6
