### ISSUE TITLE
Temporal :hourglass: coverage not accurate

### ISSUE THREAD

**Issue by kassyray** [GBADsInformatics/GBADsDataSearchUI#17]
UI does not reflect the time period in the metadata return 

<img width="705" alt="image" src="https://github.com/GBADsInformatics/GBADsDataSearchUI/assets/44474665/54bfdc81-a4f8-4683-afc6-d595ab99a0e1">

See temporalCoverage from metadata return
https://gbadske.org/meta-api/datasets?countries=Canada&species=Cattle

**Comment by MatthewSzurkowski** [comment]
Fixed with 0ce071a
