### ISSUE TITLE
Show data loading on tab switch (search screen) 🖱️ 

### ISSUE THREAD

**Issue by MatthewSzurkowski** [GBADsInformatics/GBADsDataSearchUI#4]
When a user clicks on on of the tabs (data, literature, query) on the search screen
The loading table should be displayed and the new data should then be loaded

**Comment by MatthewSzurkowski** [comment]
Partially closed... this will need to be reviewed once the routes for the data, literature, and query parts are created.

**Comment by kassyray** [comment]
We need to double check with Deb but in December at the Liverpool meeting we discussed prioritization and we might keep literature as a 'future feature' (focus on the data for now)

**Comment by MatthewSzurkowski** [comment]
@kassyray sounds good, thanks for keeping me in the loop! 😄

**Comment by MatthewSzurkowski** [comment]
Closing this ticket. Removed the Literature tab with feed11a81e655b66a5a110eb0a4938e87414d4a8
